services:
  fastapiApp:
      image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      container_name: fastapiApp
      build:
        dockerfile: Dockerfile.Deploy
      ports:
        - ${APP_PORT}:${APP_PORT}
      env_file: .env