services:
  fastapiApp:
    image: fastapiapp
    container_name: fastapiApp
    build:
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file: .env
    healthcheck:
      test: curl localhost:8000
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 10s