services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /db/database
    volumes:
      - ./db/postgres:/db/postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass password
    volumes:
      - ./db/redis:/db/redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  fastapiApp:
    image: fastapiapp
    container_name: fastapiApp
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - postgres
      - redis
